name: Generate JOSS PDF

on:
  push:
    branches: [ main, master ]
    paths: [ 'paper.md', 'paper.bib' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'paper.md', 'paper.bib' ]
  workflow_dispatch:  # Manual trigger

jobs:
  paper:
    runs-on: ubuntu-latest
    name: PDF Generator
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF
        uses: openjournals/pandoc-action@main
        with:
          journal: joss
          path: paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf
          retention-days: 30
